version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    restart: always

  redis_ui:
    image: redislabs/redisinsight
    depends_on:
      - redis
    container_name: redis_ui
    ports:
      - 8001:8001

  proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - 8080:80
    depends_on:
      - redis
      - web_check_locations
    volumes:
      - ./nginx.development.conf:/etc/nginx/nginx.conf:ro
    restart: always

  web_check_locations:
    build: .
    depends_on:
      - redis
    container_name: web_check_locations
    ports:
      - 5000:5000
    restart: always
